### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by eblanca** [linuxmint/lmde-3-cinnamon-beta#1]
I installed lmde3 into a vbox virtual machine.
I'm behind a proxy, so when into the live session I had to create my own /etc/apt/apt.conf in order to let synaptic update its files. It worked pretty well. Now, after installing the OS on the (virtual) hd, I see there is no custom apt.conf and I need to re-create it.
I would expect my custom file to be copied also for maximum ease-of-use, is this done on purpose this way?

Edit: I used your installer (link on the desktop), not calamares.

**Comment by clefebvre** [comment]
Hi @eblanca,

This is by design, almost all live sessions and installers work this way. The live session is an extracted version of the squashfs in memory. The installer copies another extracted version of the squashfs, not the one your using in memory. Consequently, any changes you make to the live session have no effect on the installed system.
