### ISSUE TITLE
live-installer: l10n issue

### ISSUE THREAD

**Issue by dfadeur** [linuxmint/lmde-3-cinnamon-beta#12]
when choosing french for installation, the partition window is in deutch

**Comment by clefebvre** [comment]
dutch timezone?

**Comment by dfadeur** [comment]
no Europe/Brussels and all the other windows are in french

**Comment by NikoKrause** [comment]
Screenshot? What do you mean with "deutch": Deutsch or Dutch?

**Comment by dfadeur** [comment]
i mean Deutsch no screenshot, installation also done

**Comment by xenopeek** [comment]
Confirming this issue. If the timezone location's associated language differs from the language the user selected, the buttons on the partitioning screen use the wrong language.

For example here is a screenshot of the partitioning screen with previously having selected French (France) as language and Europe/Brussels as timezone location. The screen is in French except for the underlined buttons, which are in Dutch (not Deutsch, that would be German).

![screenshot](https://i.imgur.com/ovQkCxa.png)

You'll also spot the bottom buttons are in English. I haven't looked into that but issue #14 covers that specifically.

This issue seems to have its cause in the `self.build_lang_list()` call just before the partitioning screen's text labels are created, here https://github.com/linuxmint/live-installer/blob/master/usr/lib/live-installer/frontend/gtk_interface.py#L156. Apparently something in `self.build_lang_list()` affects the gettext calls (the `.set_label(_('TEXT'))` method calls) after it some way so that they use the language from the timezone location instead of the language the user selected. Unexplainably it does not affect _all_ gettext calls after it though.

Moving the `self.build_lang_list()` call to _after_ the block of code starting with `#partitions` a few lines down (so move it from line 156 to say line 183) makes the issue go away though I'd call it a workaround and not a solution.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/live-installer/commit/5536420caebcac1558417d47b92fd31b070c3424
