### ISSUE TITLE
live-installer: Can't select other filesystems to install on

### ISSUE THREAD

**Issue by mvdberge** [linuxmint/lmde-3-cinnamon-beta#15]
When going through the installation process, I wanted to install the root partition / on a btrfs partition. This is not available to choose in general (should it be supported? I would like to have it!). Still, if I want to choose any other partition type like xfs, I can't click on the "OK" button, nor on the "Cancel" button - the only way to exit the selection is to close the window with the "X" in the title.

Maybe it's only a problem because I clicked on "Edit partitions" before and formatted the ext4 rootfs to btrfs manually? Still, this error should not appear.

**Comment by mvdberge** [comment]
I just found out that somehow the installer gets my selection of "xfs" as the rootfs, see attached screenshot - although the windows is not closed regularly.

![screenshot](https://user-images.githubusercontent.com/8587894/43512152-9d99075e-957a-11e8-87f3-8fef79089173.png)

**Comment by clefebvre** [comment]
https://github.com/linuxmint/live-installer/commit/cf227ed428511cc56824ac00b4e2ffe1311268c5 fixes btrfs being missing.

Partition edit dialog is fixed by:
https://github.com/linuxmint/live-installer/commit/d943b3a12f491c82331ae5173eab96b3804dc3c6
https://github.com/linuxmint/live-installer/commit/64d73ad1352e8f3eda9e8ed4e45eceae7af7dddb
