### ISSUE TITLE
Backlight Not Responsive

### ISSUE THREAD

**Issue by darethehair** [linuxmint/lmde-3-cinnamon-beta#18]
The 'xbacklight' utility does not respond.  Eventually found a solution here -- specifically for my 'Intel' system:

[Fix Brightness Control Not Working for Ubuntu & Linux Mint]
https://itsfoss.com/fix-brightness-ubuntu-1310/

**Comment by xenopeek** [comment]
Controlling screen brightness is often problematic due to ACPI quirks and bugs on various motherboards. Often there may be other ways to control screen brightness, or ways to work around the quirks and bugs. For more info see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=651741#88. This isn't specific to LMDE 3 beta nor is there a generic solution to this so closing.
