### ISSUE TITLE
Calamares Installer

### ISSUE THREAD

**Issue by mexsudo** [linuxmint/lmde-3-cinnamon-beta#2]
Calamares Installer is not shown on the desktop.

Partition Labels:
existing partition labels are not shown
no provision to label new partitions

Swap:
all existing swap partitions are mounted automatically, even the swaps on the other drives on the system.
there is no provision to deselect mounting any of them.
*potentially this will cause boot issues if there are changes made to other systems on the same machine.

**Comment by clefebvre** [comment]
Thanks @mexsudo,

This isn't configurable in Calamares so it should be reported to them directly https://github.com/calamares/calamares.

Before doing so, make sure they aren't already aware of the issue, or that they haven't already fixed it in later versions of Calamares. For info, we're using version 3.1.13 in LMDE 3 (we couldn't run a newer version due to the slightly older libraries present in Debian Stretch).

**Comment by clefebvre** [comment]
I took note of the desktop link also. We weren't planning on showing it there, but we might reconsider for the stable release.
