### ISSUE TITLE
WIFI detected, No internet connection BUG?

### ISSUE THREAD

**Issue by trytip** [linuxmint/lmde-3-cinnamon-beta#22]
hello Clem:
you closed my no internet connection issue.  i stated that my wifi is able to connect with ubuntu 12.04 and drivers are not the issue here?  the issue was resolved by:
`sudo nano /etc/NetworkManager/NetworkManager.conf`
adding the line:
```
[device]
wifi.scan-rand-mac-address=no
```
then restart network:
`sudo systemctl restart NetworkManager`

**Comment by xenopeek** [comment]
NetworkManager uses MAC address randomization during scanning for Wifi networks. Not for connecting to a Wifi network. This has been in place for a long while, see: https://blogs.gnome.org/thaller/2016/08/26/mac-address-spoofing-in-networkmanager-1-4-0/. At the time (late 2016) some users experienced problems on Debian with connecting to Wifi, like this bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835822. That bug has been fixed for Debian 9 though.

LMDE 3 uses NetworkManager (and wpa_supplicant) from the Debian 9 repositories so this doesn't look to be a general issue with the LMDE 3 beta but an issue specific to your network device driver and/or your network configuration. Likely the former. Ubuntu 12.04 didn't have the MAC address randomization during Wifi scanning so likely that's why your system worked fine with that. As noted in other places, the configuration change you did is the known workaround for systems that have this issue. Mind that Ubuntu 12.04 reached end-of-life as of April last year, unless you're paying for extended security maintenance (https://www.ubuntu.com/support/esm).

Closing this for now as not an issue in the beta.
